### PR TITLE
Added new sample - Hide SharePoint list from site contents

### PR DESCRIPTION
**Pull request by michelcarlo**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no      |
| New feature?    | no                               |
| New sample?     |  yes                               |
| Related issues? | None |

## Solution Details

|        Q                                                  |                    A                    |
| --------------------------------------------------------- | --------------------------------------- |
| Solution requires premium license                         | no                       |
| Which connectors are used?                                | SharePoint, Outlook |
| Solution uses on-premises connectors?                     | no                         |
| Solution uses custom connectors?                          | no                           |

## What's in this Pull Request?

New sample: Power Automate Flow to hide or show a SharePoint list on the Site Contents page.

hideListAnimation

### CODE REVIEW

**Comment by PopWarner** [comment]
Thanks again @michelcarlo. Will get this processed soon as well. You rock! 🧡💜🤩

**Comment by michelcarlo** [comment]
> Thanks again @michelcarlo. Will get this processed soon as well. You rock! 🧡💜🤩

Cheers David!!!🤩🤩🤩

**Comment by aprildunnam** [comment]
Hi @michelcarlo - same for this one.  Could you please provide the zip file?

**Comment by michelcarlo** [comment]
> Hi @michelcarlo - same for this one. Could you please provide the zip file?

Hey April, 

Sure, just submitted it.

**Pull request merged**
