### PR TITLE
Set Home Page Template

### PR DESCRIPTION
**Pull request by skmckenFVSD**
> We're so eager to add your sample to this repository as soon as possible, but we need all samples follow the same structure. 
> To make sure we process it as soon as possible, make sure to follow [these instructions](https://github.com/pnp/powerautomate-samples/wiki/How-to-submit-a-Power-Automate-sample).

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | N/A |

## Solution Details

|        Q                                                  |                    A                    |
| --------------------------------------------------------- | --------------------------------------- |
| Solution requires premium license                         | yes                               |
| Which connectors are used?                                | SharePoint |
| Solution uses on-premises connectors?                     | no                               |
| Solution uses custom connectors?                          | no                               |

## What's in this Pull Request?

Two Power Automate Flows with Source Code and Readme for Install

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @skmckenFVSD, I'll process your pull request this week.

**Comment by hugoabernier** [comment]
Thank you @skmckenFVSD. This is a great sample!

**Comment by skmckenFVSD** [comment]
> Thanks @hugoabernier. Hopefully I managed to work through the process for contributing without too many issues.

**Comment by hugoabernier** [comment]
You did great @skmckenFVSD... but you know how you get better at it? By doing *more* 😊.

I hope to see more contributions from you in the future!

**Pull request merged**
