### PR TITLE
title change

### LINKED ISSUE #40: Link to the Sample is wrong.
### Sample

https://github.com/pnp/powerautomate-samples/tree/main/samples/azure-http-key-vault

### Author(s)

Divya Akula

### What happened?

While I understand that this is not a Bug directly related to the code provided, I've not found a way to raise awareness to this issue elsewhere.  

The GitHub link provided on [this page](https://adoption.microsoft.com/en-us/sample-solution-gallery/sample/pnp-powerautomate-samples-azure-http-key-vault/) is pointing to the wrong Sample in the PnP repository. 

The GitHub link is pointing to "Always respond to a request" sample, rather the "azure-http-key-vault" sample. In addition, the azure-http-key-vault sample's READ ME has a wrong title with "Pattern: Always respond to a request". It seems like a copy-paste gone wrong.

### Steps to reproduce

1. Visit https://adoption.microsoft.com/en-us/sample-solution-gallery/?product=Power+Automate&sortby=creationDateTime-true&page=1
2. Click on the View on GitHub
3. Observe that it is pulling up the wrong folder. 

### Expected behavior

It should pull up the correct code.

### PR DESCRIPTION
**Pull request by ValerasNarbutas**
> We're so eager to add your sample to this repository as soon as possible, but we need all samples follow the same structure. 
> To make sure we process it as soon as possible, make sure to follow [these instructions](https://github.com/pnp/powerautomate-samples/wiki/How-to-submit-a-Power-Automate-sample).

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        |  yes                             |
| New feature?    | no                              |
| New sample?     | no                              |
| Related issues? | fixes #40  , partially #Y, mentioned in #Z |

## Solution Details

|        Q                                                  |                    A                    |
| --------------------------------------------------------- | --------------------------------------- |
| Solution requires premium license                         | no                          |
| Which connectors are used?                                | e.g.: SharePoint, DataVerse, DataVerse for Teams, Outlook, DocuSign, etc.  |
| Solution uses on-premises connectors?                     | no                              |
| Solution uses custom connectors?                          | no                              |

## What's in this Pull Request?

fixing issue #40

### CODE REVIEW

**Comment by ValerasNarbutas** [comment]
had typo in description, this fix is for issue #40

**Comment by ValerasNarbutas** [comment]
@aprildunnam good afternoon, 
this should resolve wrong link issue #40 

Thanks,

**Comment by aprildunnam** [comment]
Thanks for submitting the PR @ValerasNarbutas.  Apologies for the delay, it's been very busy around here. Thanks for your patience!

**Comment by ValerasNarbutas** [comment]
> Thanks for submitting the PR @ValerasNarbutas. Apologies for the delay, it's been very busy around here. Thanks for your patience!

👋 Thank you for getting back to me @aprildunnam  🤗 No worries about the delay, I totally understand that things can get busy.   🤞

**Pull request merged**
